name: Preview Fork PR

on:
  workflow_run:
    workflows: ["Build Fork PR"]
    types:
      - completed

jobs:
  build:
    name: Deploying to surge
    uses: tlylt/markbind-reusable-workflows/.github/workflows/fork-preview.yml@main
