name: Reuse

on:
  workflow_call:
    inputs:
      version:
        description: specify a version of markbind to use. e.g. 3.1.1
        default: 'latest'
        type: string
      target_branch:
        default: 'gh-pages'
        type: string
      

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install right version
        run: npm i -g markbind-cli@${{ inputs.version }}
      - name: build
        run: markbind build