name: Reuse

on:
  workflow_call:
    inputs:
      version:
        default: 'latest'
        type: string

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install right version
        run: npm i -g markbind-cli@${{ inputs.version }}
      - name: build
        run: markbind build
      - name: print
        run: markbind -V