name: Call a reusable workflow
on:
  push:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tlylt/test-md/.github/workflows/reusable.yml@main
        with:
          version: 3.1.0