name: Test failure

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: dev docs
    defaults:
      run:
        shell: bash
        working-directory: docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: |
          ls
          npm run build
      - name: Display the dir
        run: echo $PWD
        shell: bash
      - uses: actions/github-script@v6
        id: check-error
        with:
          script: |
            const fs = require('fs');
            // check if build directory exists
            const dir = './docs/_site';

            // check if directory exists
            if (fs.existsSync(dir)) {
                console.log('Directory exists!');
            } else {
                console.log('Directory not found.');
                core.setFailed('Documentation Build Error!')
            }
      - name: Deploy UG on release
        if: ${{ success() && github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          # markbind deploy --ci