name: Test failure
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i -g markbind-cli
      - run: markbind build
      - name: Display the path
        run: echo $PATH
        shell: bash