name: Test failure
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i -g markbind-cli@3.1.1
      - run: markbind build
      - uses: actions/github-script@v6
        id: check-error
        with:
          script: |
            const fs = require('fs');

            // directory to check if exists
            const dir = './_site';

            // check if directory exists
            if (fs.existsSync(dir)) {
                console.log('Directory exists!');
            } else {
                console.log('Directory not found.');
                core.setFailed('Build Error!')
            }
      - name: Display the path
        run: echo $PATH
        shell: bash